/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppContratoRouteImport } from './routes/_app.contrato'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDocumentosRouteImport } from './routes/_app.documentos'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppProjetosRouteImport } from './routes/_app.projetos'
import { Route as AppSuporteRouteImport } from './routes/_app.suporte'
import { Route as CTokenRouteImport } from './routes/c.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContratoRoute = AppContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contrato': typeof AppContratoRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentos': typeof AppDocumentosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/projetos': typeof AppProjetosRoute
  '/suporte': typeof AppSuporteRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contrato': typeof AppContratoRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentos': typeof AppDocumentosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/projetos': typeof AppProjetosRoute
  '/suporte': typeof AppSuporteRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/contrato': typeof AppContratoRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documentos': typeof AppDocumentosRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/projetos': typeof AppProjetosRoute
  '/_app/suporte': typeof AppSuporteRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contrato'
    | '/dashboard'
    | '/documentos'
    | '/financeiro'
    | '/projetos'
    | '/suporte'
    | '/c/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contrato'
    | '/dashboard'
    | '/documentos'
    | '/financeiro'
    | '/projetos'
    | '/suporte'
    | '/c/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/contrato'
    | '/_app/dashboard'
    | '/_app/documentos'
    | '/_app/financeiro'
    | '/_app/projetos'
    | '/_app/suporte'
    | '/c/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CTokenRoute: typeof CTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contrato': {
      id: '/_app/contrato'
      path: '/contrato'
      fullPath: '/contrato'
      preLoaderRoute: typeof AppContratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos': {
      id: '/_app/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos': {
      id: '/_app/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suporte': {
      id: '/_app/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppContratoRoute: typeof AppContratoRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppSuporteRoute: typeof AppSuporteRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContratoRoute: AppContratoRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppSuporteRoute: AppSuporteRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CTokenRoute: CTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
