/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppContractGeneratorRouteImport } from './routes/app.contract-generator'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppRisksRouteImport } from './routes/app.risks'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppWikiRouteImport } from './routes/app.wiki'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as CandidaturaIdRouteImport } from './routes/candidatura.$id'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as PortalAuthRouteImport } from './routes/portal.auth'
import { Route as PortalContratoRouteImport } from './routes/portal.contrato'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalDocumentosRouteImport } from './routes/portal.documentos'
import { Route as PortalFinanceiroRouteImport } from './routes/portal.financeiro'
import { Route as PortalProjetosRouteImport } from './routes/portal.projetos'
import { Route as PortalSuporteRouteImport } from './routes/portal.suporte'
import { Route as TriagemTokenRouteImport } from './routes/triagem.$token'
import { Route as AppClientsIndexRouteImport } from './routes/app.clients.index'
import { Route as AppClientsIdRouteImport } from './routes/app.clients.$id'
import { Route as AppContractModelsIndexRouteImport } from './routes/app.contract-models.index'
import { Route as AppContractModelsIdRouteImport } from './routes/app.contract-models.$id'
import { Route as AppFreelancersIndexRouteImport } from './routes/app.freelancers.index'
import { Route as AppFreelancersIdRouteImport } from './routes/app.freelancers.$id'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'
import { Route as AppProjectsNewRouteImport } from './routes/app.projects.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractGeneratorRoute = AppContractGeneratorRouteImport.update({
  id: '/contract-generator',
  path: '/contract-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppRisksRoute = AppRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppWikiRoute = AppWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => AppRoute,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidaturaIdRoute = CandidaturaIdRouteImport.update({
  id: '/candidatura/$id',
  path: '/candidatura/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAuthRoute = PortalAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContratoRoute = PortalContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFinanceiroRoute = PortalFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjetosRoute = PortalProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSuporteRoute = PortalSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => PortalRoute,
} as any)
const TriagemTokenRoute = TriagemTokenRouteImport.update({
  id: '/triagem/$token',
  path: '/triagem/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContractModelsIndexRoute = AppContractModelsIndexRouteImport.update({
  id: '/contract-models/',
  path: '/contract-models/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractModelsIdRoute = AppContractModelsIdRouteImport.update({
  id: '/contract-models/$id',
  path: '/contract-models/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFreelancersIndexRoute = AppFreelancersIndexRouteImport.update({
  id: '/freelancers/',
  path: '/freelancers/',
  getParentRoute: () => AppRoute,
} as any)
const AppFreelancersIdRoute = AppFreelancersIdRouteImport.update({
  id: '/freelancers/$id',
  path: '/freelancers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/app/contract-generator': typeof AppContractGeneratorRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/risks': typeof AppRisksRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/wiki': typeof AppWikiRoute
  '/c/$token': typeof CTokenRoute
  '/candidatura/$id': typeof CandidaturaIdRoute
  '/p/$token': typeof PTokenRoute
  '/portal/auth': typeof PortalAuthRoute
  '/portal/contrato': typeof PortalContratoRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/projetos': typeof PortalProjetosRoute
  '/portal/suporte': typeof PortalSuporteRoute
  '/triagem/$token': typeof TriagemTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/contract-models/$id': typeof AppContractModelsIdRoute
  '/app/freelancers/$id': typeof AppFreelancersIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/contract-models/': typeof AppContractModelsIndexRoute
  '/app/freelancers/': typeof AppFreelancersIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/app/contract-generator': typeof AppContractGeneratorRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/risks': typeof AppRisksRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/wiki': typeof AppWikiRoute
  '/c/$token': typeof CTokenRoute
  '/candidatura/$id': typeof CandidaturaIdRoute
  '/p/$token': typeof PTokenRoute
  '/portal/auth': typeof PortalAuthRoute
  '/portal/contrato': typeof PortalContratoRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/projetos': typeof PortalProjetosRoute
  '/portal/suporte': typeof PortalSuporteRoute
  '/triagem/$token': typeof TriagemTokenRoute
  '/app': typeof AppIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/contract-models/$id': typeof AppContractModelsIdRoute
  '/app/freelancers/$id': typeof AppFreelancersIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/contract-models': typeof AppContractModelsIndexRoute
  '/app/freelancers': typeof AppFreelancersIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/app/contract-generator': typeof AppContractGeneratorRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/risks': typeof AppRisksRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/wiki': typeof AppWikiRoute
  '/c/$token': typeof CTokenRoute
  '/candidatura/$id': typeof CandidaturaIdRoute
  '/p/$token': typeof PTokenRoute
  '/portal/auth': typeof PortalAuthRoute
  '/portal/contrato': typeof PortalContratoRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/projetos': typeof PortalProjetosRoute
  '/portal/suporte': typeof PortalSuporteRoute
  '/triagem/$token': typeof TriagemTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/contract-models/$id': typeof AppContractModelsIdRoute
  '/app/freelancers/$id': typeof AppFreelancersIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/contract-models/': typeof AppContractModelsIndexRoute
  '/app/freelancers/': typeof AppFreelancersIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/portal'
    | '/app/contract-generator'
    | '/app/documents'
    | '/app/finance'
    | '/app/notifications'
    | '/app/risks'
    | '/app/suporte'
    | '/app/wiki'
    | '/c/$token'
    | '/candidatura/$id'
    | '/p/$token'
    | '/portal/auth'
    | '/portal/contrato'
    | '/portal/dashboard'
    | '/portal/documentos'
    | '/portal/financeiro'
    | '/portal/projetos'
    | '/portal/suporte'
    | '/triagem/$token'
    | '/app/'
    | '/app/clients/$id'
    | '/app/contract-models/$id'
    | '/app/freelancers/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/clients/'
    | '/app/contract-models/'
    | '/app/freelancers/'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/app/contract-generator'
    | '/app/documents'
    | '/app/finance'
    | '/app/notifications'
    | '/app/risks'
    | '/app/suporte'
    | '/app/wiki'
    | '/c/$token'
    | '/candidatura/$id'
    | '/p/$token'
    | '/portal/auth'
    | '/portal/contrato'
    | '/portal/dashboard'
    | '/portal/documentos'
    | '/portal/financeiro'
    | '/portal/projetos'
    | '/portal/suporte'
    | '/triagem/$token'
    | '/app'
    | '/app/clients/$id'
    | '/app/contract-models/$id'
    | '/app/freelancers/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/clients'
    | '/app/contract-models'
    | '/app/freelancers'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/portal'
    | '/app/contract-generator'
    | '/app/documents'
    | '/app/finance'
    | '/app/notifications'
    | '/app/risks'
    | '/app/suporte'
    | '/app/wiki'
    | '/c/$token'
    | '/candidatura/$id'
    | '/p/$token'
    | '/portal/auth'
    | '/portal/contrato'
    | '/portal/dashboard'
    | '/portal/documentos'
    | '/portal/financeiro'
    | '/portal/projetos'
    | '/portal/suporte'
    | '/triagem/$token'
    | '/app/'
    | '/app/clients/$id'
    | '/app/contract-models/$id'
    | '/app/freelancers/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/clients/'
    | '/app/contract-models/'
    | '/app/freelancers/'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRouteWithChildren
  CTokenRoute: typeof CTokenRoute
  CandidaturaIdRoute: typeof CandidaturaIdRoute
  PTokenRoute: typeof PTokenRoute
  TriagemTokenRoute: typeof TriagemTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contract-generator': {
      id: '/app/contract-generator'
      path: '/contract-generator'
      fullPath: '/app/contract-generator'
      preLoaderRoute: typeof AppContractGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risks': {
      id: '/app/risks'
      path: '/risks'
      fullPath: '/app/risks'
      preLoaderRoute: typeof AppRisksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wiki': {
      id: '/app/wiki'
      path: '/wiki'
      fullPath: '/app/wiki'
      preLoaderRoute: typeof AppWikiRouteImport
      parentRoute: typeof AppRoute
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatura/$id': {
      id: '/candidatura/$id'
      path: '/candidatura/$id'
      fullPath: '/candidatura/$id'
      preLoaderRoute: typeof CandidaturaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/auth': {
      id: '/portal/auth'
      path: '/auth'
      fullPath: '/portal/auth'
      preLoaderRoute: typeof PortalAuthRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contrato': {
      id: '/portal/contrato'
      path: '/contrato'
      fullPath: '/portal/contrato'
      preLoaderRoute: typeof PortalContratoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/financeiro': {
      id: '/portal/financeiro'
      path: '/financeiro'
      fullPath: '/portal/financeiro'
      preLoaderRoute: typeof PortalFinanceiroRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projetos': {
      id: '/portal/projetos'
      path: '/projetos'
      fullPath: '/portal/projetos'
      preLoaderRoute: typeof PortalProjetosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/suporte': {
      id: '/portal/suporte'
      path: '/suporte'
      fullPath: '/portal/suporte'
      preLoaderRoute: typeof PortalSuporteRouteImport
      parentRoute: typeof PortalRoute
    }
    '/triagem/$token': {
      id: '/triagem/$token'
      path: '/triagem/$token'
      fullPath: '/triagem/$token'
      preLoaderRoute: typeof TriagemTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/$id': {
      id: '/app/clients/$id'
      path: '/clients/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contract-models/': {
      id: '/app/contract-models/'
      path: '/contract-models'
      fullPath: '/app/contract-models/'
      preLoaderRoute: typeof AppContractModelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contract-models/$id': {
      id: '/app/contract-models/$id'
      path: '/contract-models/$id'
      fullPath: '/app/contract-models/$id'
      preLoaderRoute: typeof AppContractModelsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/freelancers/': {
      id: '/app/freelancers/'
      path: '/freelancers'
      fullPath: '/app/freelancers/'
      preLoaderRoute: typeof AppFreelancersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/freelancers/$id': {
      id: '/app/freelancers/$id'
      path: '/freelancers/$id'
      fullPath: '/app/freelancers/$id'
      preLoaderRoute: typeof AppFreelancersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/projects/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContractGeneratorRoute: typeof AppContractGeneratorRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRisksRoute: typeof AppRisksRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppWikiRoute: typeof AppWikiRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppContractModelsIdRoute: typeof AppContractModelsIdRoute
  AppFreelancersIdRoute: typeof AppFreelancersIdRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppContractModelsIndexRoute: typeof AppContractModelsIndexRoute
  AppFreelancersIndexRoute: typeof AppFreelancersIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContractGeneratorRoute: AppContractGeneratorRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRisksRoute: AppRisksRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppWikiRoute: AppWikiRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppContractModelsIdRoute: AppContractModelsIdRoute,
  AppFreelancersIdRoute: AppFreelancersIdRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppContractModelsIndexRoute: AppContractModelsIndexRoute,
  AppFreelancersIndexRoute: AppFreelancersIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalAuthRoute: typeof PortalAuthRoute
  PortalContratoRoute: typeof PortalContratoRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalFinanceiroRoute: typeof PortalFinanceiroRoute
  PortalProjetosRoute: typeof PortalProjetosRoute
  PortalSuporteRoute: typeof PortalSuporteRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAuthRoute: PortalAuthRoute,
  PortalContratoRoute: PortalContratoRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalFinanceiroRoute: PortalFinanceiroRoute,
  PortalProjetosRoute: PortalProjetosRoute,
  PortalSuporteRoute: PortalSuporteRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRouteWithChildren,
  CTokenRoute: CTokenRoute,
  CandidaturaIdRoute: CandidaturaIdRoute,
  PTokenRoute: PTokenRoute,
  TriagemTokenRoute: TriagemTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
