/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as FreelancerRouteImport } from './routes/freelancer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppContractGeneratorRouteImport } from './routes/app.contract-generator'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppRisksRouteImport } from './routes/app.risks'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppWikiRouteImport } from './routes/app.wiki'
import { Route as CandidaturaIdRouteImport } from './routes/candidatura.$id'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as ClienteDashboardRouteImport } from './routes/cliente.dashboard'
import { Route as FreelancerIndexRouteImport } from './routes/freelancer.index'
import { Route as FreelancerDashboardRouteImport } from './routes/freelancer.dashboard'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as TriagemTokenRouteImport } from './routes/triagem.$token'
import { Route as AppClientsIndexRouteImport } from './routes/app.clients.index'
import { Route as AppClientsIdRouteImport } from './routes/app.clients.$id'
import { Route as AppContractModelsIndexRouteImport } from './routes/app.contract-models.index'
import { Route as AppContractModelsIdRouteImport } from './routes/app.contract-models.$id'
import { Route as AppFreelancersIndexRouteImport } from './routes/app.freelancers.index'
import { Route as AppFreelancersIdRouteImport } from './routes/app.freelancers.$id'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'
import { Route as AppProjectsNewRouteImport } from './routes/app.projects.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerRoute = FreelancerRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppContractGeneratorRoute = AppContractGeneratorRouteImport.update({
  id: '/contract-generator',
  path: '/contract-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppRisksRoute = AppRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppWikiRoute = AppWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => AppRoute,
} as any)
const CandidaturaIdRoute = CandidaturaIdRouteImport.update({
  id: '/candidatura/$id',
  path: '/candidatura/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteDashboardRoute = ClienteDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClienteRoute,
} as any)
const FreelancerIndexRoute = FreelancerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerDashboardRoute = FreelancerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FreelancerRoute,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TriagemTokenRoute = TriagemTokenRouteImport.update({
  id: '/triagem/$token',
  path: '/triagem/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContractModelsIndexRoute = AppContractModelsIndexRouteImport.update({
  id: '/contract-models/',
  path: '/contract-models/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractModelsIdRoute = AppContractModelsIdRouteImport.update({
  id: '/contract-models/$id',
  path: '/contract-models/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFreelancersIndexRoute = AppFreelancersIndexRouteImport.update({
  id: '/freelancers/',
  path: '/freelancers/',
  getParentRoute: () => AppRoute,
} as any)
const AppFreelancersIdRoute = AppFreelancersIdRouteImport.update({
  id: '/freelancers/$id',
  path: '/freelancers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/freelancer': typeof FreelancerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/contract-generator': typeof AppContractGeneratorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/risks': typeof AppRisksRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/wiki': typeof AppWikiRoute
  '/candidatura/$id': typeof CandidaturaIdRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/freelancer/dashboard': typeof FreelancerDashboardRoute
  '/p/$token': typeof PTokenRoute
  '/triagem/$token': typeof TriagemTokenRoute
  '/app/': typeof AppIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/contract-models/$id': typeof AppContractModelsIdRoute
  '/app/freelancers/$id': typeof AppFreelancersIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/contract-models/': typeof AppContractModelsIndexRoute
  '/app/freelancers/': typeof AppFreelancersIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/contract-generator': typeof AppContractGeneratorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/risks': typeof AppRisksRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/wiki': typeof AppWikiRoute
  '/candidatura/$id': typeof CandidaturaIdRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/freelancer/dashboard': typeof FreelancerDashboardRoute
  '/p/$token': typeof PTokenRoute
  '/triagem/$token': typeof TriagemTokenRoute
  '/app': typeof AppIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/freelancer': typeof FreelancerIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/contract-models/$id': typeof AppContractModelsIdRoute
  '/app/freelancers/$id': typeof AppFreelancersIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/contract-models': typeof AppContractModelsIndexRoute
  '/app/freelancers': typeof AppFreelancersIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/freelancer': typeof FreelancerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/contract-generator': typeof AppContractGeneratorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/risks': typeof AppRisksRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/wiki': typeof AppWikiRoute
  '/candidatura/$id': typeof CandidaturaIdRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/freelancer/dashboard': typeof FreelancerDashboardRoute
  '/p/$token': typeof PTokenRoute
  '/triagem/$token': typeof TriagemTokenRoute
  '/app/': typeof AppIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/contract-models/$id': typeof AppContractModelsIdRoute
  '/app/freelancers/$id': typeof AppFreelancersIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/contract-models/': typeof AppContractModelsIndexRoute
  '/app/freelancers/': typeof AppFreelancersIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/aguardando-aprovacao'
    | '/app'
    | '/auth'
    | '/cliente'
    | '/freelancer'
    | '/onboarding'
    | '/app/approvals'
    | '/app/contract-generator'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/finance'
    | '/app/notifications'
    | '/app/perfil'
    | '/app/risks'
    | '/app/suporte'
    | '/app/wiki'
    | '/candidatura/$id'
    | '/cliente/dashboard'
    | '/freelancer/dashboard'
    | '/p/$token'
    | '/triagem/$token'
    | '/app/'
    | '/cliente/'
    | '/freelancer/'
    | '/app/clients/$id'
    | '/app/contract-models/$id'
    | '/app/freelancers/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/clients/'
    | '/app/contract-models/'
    | '/app/freelancers/'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/aguardando-aprovacao'
    | '/auth'
    | '/onboarding'
    | '/app/approvals'
    | '/app/contract-generator'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/finance'
    | '/app/notifications'
    | '/app/perfil'
    | '/app/risks'
    | '/app/suporte'
    | '/app/wiki'
    | '/candidatura/$id'
    | '/cliente/dashboard'
    | '/freelancer/dashboard'
    | '/p/$token'
    | '/triagem/$token'
    | '/app'
    | '/cliente'
    | '/freelancer'
    | '/app/clients/$id'
    | '/app/contract-models/$id'
    | '/app/freelancers/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/clients'
    | '/app/contract-models'
    | '/app/freelancers'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/acesso-negado'
    | '/aguardando-aprovacao'
    | '/app'
    | '/auth'
    | '/cliente'
    | '/freelancer'
    | '/onboarding'
    | '/app/approvals'
    | '/app/contract-generator'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/finance'
    | '/app/notifications'
    | '/app/perfil'
    | '/app/risks'
    | '/app/suporte'
    | '/app/wiki'
    | '/candidatura/$id'
    | '/cliente/dashboard'
    | '/freelancer/dashboard'
    | '/p/$token'
    | '/triagem/$token'
    | '/app/'
    | '/cliente/'
    | '/freelancer/'
    | '/app/clients/$id'
    | '/app/contract-models/$id'
    | '/app/freelancers/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/clients/'
    | '/app/contract-models/'
    | '/app/freelancers/'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  FreelancerRoute: typeof FreelancerRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  CandidaturaIdRoute: typeof CandidaturaIdRoute
  PTokenRoute: typeof PTokenRoute
  TriagemTokenRoute: typeof TriagemTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer': {
      id: '/freelancer'
      path: '/freelancer'
      fullPath: '/freelancer'
      preLoaderRoute: typeof FreelancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contract-generator': {
      id: '/app/contract-generator'
      path: '/contract-generator'
      fullPath: '/app/contract-generator'
      preLoaderRoute: typeof AppContractGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risks': {
      id: '/app/risks'
      path: '/risks'
      fullPath: '/app/risks'
      preLoaderRoute: typeof AppRisksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wiki': {
      id: '/app/wiki'
      path: '/wiki'
      fullPath: '/app/wiki'
      preLoaderRoute: typeof AppWikiRouteImport
      parentRoute: typeof AppRoute
    }
    '/candidatura/$id': {
      id: '/candidatura/$id'
      path: '/candidatura/$id'
      fullPath: '/candidatura/$id'
      preLoaderRoute: typeof CandidaturaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/dashboard': {
      id: '/cliente/dashboard'
      path: '/dashboard'
      fullPath: '/cliente/dashboard'
      preLoaderRoute: typeof ClienteDashboardRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/freelancer/': {
      id: '/freelancer/'
      path: '/'
      fullPath: '/freelancer/'
      preLoaderRoute: typeof FreelancerIndexRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/dashboard': {
      id: '/freelancer/dashboard'
      path: '/dashboard'
      fullPath: '/freelancer/dashboard'
      preLoaderRoute: typeof FreelancerDashboardRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triagem/$token': {
      id: '/triagem/$token'
      path: '/triagem/$token'
      fullPath: '/triagem/$token'
      preLoaderRoute: typeof TriagemTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/$id': {
      id: '/app/clients/$id'
      path: '/clients/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contract-models/': {
      id: '/app/contract-models/'
      path: '/contract-models'
      fullPath: '/app/contract-models/'
      preLoaderRoute: typeof AppContractModelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contract-models/$id': {
      id: '/app/contract-models/$id'
      path: '/contract-models/$id'
      fullPath: '/app/contract-models/$id'
      preLoaderRoute: typeof AppContractModelsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/freelancers/': {
      id: '/app/freelancers/'
      path: '/freelancers'
      fullPath: '/app/freelancers/'
      preLoaderRoute: typeof AppFreelancersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/freelancers/$id': {
      id: '/app/freelancers/$id'
      path: '/freelancers/$id'
      fullPath: '/app/freelancers/$id'
      preLoaderRoute: typeof AppFreelancersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/projects/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppContractGeneratorRoute: typeof AppContractGeneratorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRisksRoute: typeof AppRisksRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppWikiRoute: typeof AppWikiRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppContractModelsIdRoute: typeof AppContractModelsIdRoute
  AppFreelancersIdRoute: typeof AppFreelancersIdRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppContractModelsIndexRoute: typeof AppContractModelsIndexRoute
  AppFreelancersIndexRoute: typeof AppFreelancersIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppContractGeneratorRoute: AppContractGeneratorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRisksRoute: AppRisksRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppWikiRoute: AppWikiRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppContractModelsIdRoute: AppContractModelsIdRoute,
  AppFreelancersIdRoute: AppFreelancersIdRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppContractModelsIndexRoute: AppContractModelsIndexRoute,
  AppFreelancersIndexRoute: AppFreelancersIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ClienteRouteChildren {
  ClienteDashboardRoute: typeof ClienteDashboardRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteDashboardRoute: ClienteDashboardRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

interface FreelancerRouteChildren {
  FreelancerDashboardRoute: typeof FreelancerDashboardRoute
  FreelancerIndexRoute: typeof FreelancerIndexRoute
}

const FreelancerRouteChildren: FreelancerRouteChildren = {
  FreelancerDashboardRoute: FreelancerDashboardRoute,
  FreelancerIndexRoute: FreelancerIndexRoute,
}

const FreelancerRouteWithChildren = FreelancerRoute._addFileChildren(
  FreelancerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoNegadoRoute: AcessoNegadoRoute,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ClienteRoute: ClienteRouteWithChildren,
  FreelancerRoute: FreelancerRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  CandidaturaIdRoute: CandidaturaIdRoute,
  PTokenRoute: PTokenRoute,
  TriagemTokenRoute: TriagemTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
